# app configuration
spring.application.name=stock-service
server.port=0

# database configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/stock-service}
spring.data.mongodb.database=stock-service

# eureka configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka